services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: '1471027Demo'
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - ecommerce-network

  userservice:
    container_name: userservice

    build:
      context: ./Services/UserService
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - ecommerce-network

  productservice:
    container_name: productservice
    build:
      context: ./Services/ProductService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - ecommerce-network

  orderservice:
    container_name: orderservice
    build:
      context: .
      dockerfile: Services/OrderService/Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - ecommerce-network

  gatewayservice:
    container_name: gatewayservice
    build:
      context: .
      dockerfile: GatewayService/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - userservice
      - productservice
      - orderservice
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
